package com.revature.services;

public enum ResponseType {
    INVALID_USER,
    INVALID_EMAIL,
    ACCOUNT_EXIST,
    INVALID_PASSWORD,
    INVALID_FIELDS,
    INVALID_CATEGORY,
    INVALID_SELLER,
    INVALID_PRODUCT,
    INSUFFICIENT_ORDERS,
    SUCCESS,
    UNKNOWN_ERROR,
    INSUFFICIENT_BALANCE,
    USER_NOT_FOUND,
    ORDER_ALREADY_COMPLETED
}